-- Amazon Advances V2: العقوبات والمكافآت وعقوبة الغياب
-- شغّل هذا الملف في Supabase SQL Editor مرة واحدة.

create table if not exists public.advance_penalties (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.employees(id) on delete restrict,
  amount numeric(14,2) not null check (amount > 0),
  penalty_type text not null default 'general',
  record_date date not null default current_date,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.advance_rewards (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.employees(id) on delete restrict,
  amount numeric(14,2) not null check (amount > 0),
  record_date date not null default current_date,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.advance_penalties enable row level security;
alter table public.advance_rewards enable row level security;

-- النظام الحالي يستخدم دخولًا مخصصًا وليس Supabase Auth، لذلك هذه الصلاحيات
-- تطابق نمط الجداول الحالية في المشروع. الصلاحيات الفعلية للمدير/المانح
-- تبقى في واجهة النظام وRPCs الموجودة.
grant select, insert, update, delete on public.advance_penalties to anon, authenticated;
grant select, insert, update, delete on public.advance_rewards to anon, authenticated;
grant usage, select on sequence public.advance_penalties_id_seq to anon, authenticated;
grant usage, select on sequence public.advance_rewards_id_seq to anon, authenticated;

drop policy if exists "anon_select_advance_penalties" on public.advance_penalties;
drop policy if exists "anon_insert_advance_penalties" on public.advance_penalties;
drop policy if exists "anon_update_advance_penalties" on public.advance_penalties;
drop policy if exists "anon_delete_advance_penalties" on public.advance_penalties;
create policy "anon_select_advance_penalties" on public.advance_penalties for select to anon, authenticated using (true);
create policy "anon_insert_advance_penalties" on public.advance_penalties for insert to anon, authenticated with check (true);
create policy "anon_update_advance_penalties" on public.advance_penalties for update to anon, authenticated using (true) with check (true);
create policy "anon_delete_advance_penalties" on public.advance_penalties for delete to anon, authenticated using (true);

drop policy if exists "anon_select_advance_rewards" on public.advance_rewards;
drop policy if exists "anon_insert_advance_rewards" on public.advance_rewards;
drop policy if exists "anon_update_advance_rewards" on public.advance_rewards;
drop policy if exists "anon_delete_advance_rewards" on public.advance_rewards;
create policy "anon_select_advance_rewards" on public.advance_rewards for select to anon, authenticated using (true);
create policy "anon_insert_advance_rewards" on public.advance_rewards for insert to anon, authenticated with check (true);
create policy "anon_update_advance_rewards" on public.advance_rewards for update to anon, authenticated using (true) with check (true);
create policy "anon_delete_advance_rewards" on public.advance_rewards for delete to anon, authenticated using (true);

-- نفس واقعة الغياب في نفس اليوم لا يمكن تسجيل عقوبتها مرتين.
create unique index if not exists uq_advance_absence_penalty_once
on public.advance_penalties(employee_id, record_date)
where penalty_type = 'absence';

create index if not exists idx_advance_penalties_employee_date
on public.advance_penalties(employee_id, record_date desc);
create index if not exists idx_advance_rewards_employee_date
on public.advance_rewards(employee_id, record_date desc);
